#!/bin/bash

reqpack=( "graphics" "oberdiek" "fancyvrb" "fvextra" "upquote" "float" "latex" "tools" "ifplatform" "etoolbox" "xstring" "xcolor" "lineno" "framed" )
for pckg in "${reqpack[@]}"; do
    output="$(tlmgr --no-persistent-downloads info "${pckg}")"
    installed="$(printf "%s\n" "${output}" | grep "installed:" | awk 'BEGIN { FS = ":   " } ; {print $2 }')"
    if [[ "${installed}" == "No" ]]; then
        ## tlmgr --no-persistent-downloads install "${pckg}"
    fi
done

exit
