#! /bin/bash

## Preamble.
cd ~/"laptop02_MasAr/Graphics/"

## Store name of resulting .pdf file in variable "output".
output="Handouts/MasAr_Handout_2017-09-04_Beech_3Terms.pdf"

## Create array containing the .pdf files to be concatenated.
pdfs=(

    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_ni_Mu.pdf"
    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_sigma_gha_psh100.EKL.I_ni_Mu.pdf"
    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_ni_Mu.pdf"
    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_sigma_gha_psh100.EKL.I_ni_Mu.pdf"

    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_ni_Overview.pdf"
    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_sigma_gha_psh100.EKL.I_ni_Overview.pdf"
    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_ni_Overview.pdf"
    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_sigma_gha_psh100.EKL.I_ni_Overview.pdf"

)

## Rund "pdftk".
pdftk "${pdfs[@]}" cat output "${output}"

## Store name of resulting .pdf file in variable "output".
output="Handouts/MasAr_Handout_2017-09-04_Beech_4Terms.pdf"

## Create array containing the .pdf files to be concatenated.
pdfs=(

    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_psNORTH.UTM_ni_Mu.pdf"
    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_psNORTH.UTM_sigma_gha_psh100.EKL.I_ni_Mu.pdf"
    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_psNORTH.UTM_ni_Mu.pdf"
    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_psNORTH.UTM_sigma_gha_psh100.EKL.I_ni_Mu.pdf"

    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_psNORTH.UTM_ni_Overview.pdf"
    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_psNORTH.UTM_sigma_gha_psh100.EKL.I_ni_Overview.pdf"
    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_psNORTH.UTM_ni_Overview.pdf"
    "Models/GAMLSS/bart.beech.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_psNORTH.UTM_sigma_gha_psh100.EKL.I_ni_Overview.pdf"

)

## Rund "pdftk".
pdftk "${pdfs[@]}" cat output "${output}"

## Store name of resulting .pdf file in variable "output".
output="Handouts/MasAr_Handout_2017-09-04_Spruce_3Terms_Linear.pdf"

## Create array containing the .pdf files to be concatenated.
pdfs=(

    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_ni_Mu.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_sigma_gha_psh100.EKL.I_ni_Mu.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_ni_Mu.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_sigma_gha_psh100.EKL.I_ni_Mu.pdf"

    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_ni_Overview.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_sigma_gha_psh100.EKL.I_ni_Overview.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_ni_Overview.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_sigma_gha_psh100.EKL.I_ni_Overview.pdf"

)

## Rund "pdftk".
pdftk "${pdfs[@]}" cat output "${output}"

## Store name of resulting .pdf file in variable "output".
output="Handouts/MasAr_Handout_2017-09-04_Spruce_3Terms_Splines.pdf"

## Create array containing the .pdf files to be concatenated.
pdfs=(

    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_ni_Mu.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_sigma_gha_psh100.EKL.I_ni_Mu.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_ni_Mu.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_sigma_gha_psh100.EKL.I_ni_Mu.pdf"

    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_ni_Overview.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_sigma_gha_psh100.EKL.I_ni_Overview.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_ni_Overview.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_sigma_gha_psh100.EKL.I_ni_Overview.pdf"

)

## Rund "pdftk".
pdftk "${pdfs[@]}" cat output "${output}"

## Store name of resulting .pdf file in variable "output".
output="Handouts/MasAr_Handout_2017-09-04_Spruce_4Terms_Linear.pdf"

## Create array containing the .pdf files to be concatenated.
pdfs=(

    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_NORTH.UTM_ni_Mu.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_NORTH.UTM_sigma_gha_psh100.EKL.I_ni_Mu.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_NORTH.UTM_ni_Mu.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_NORTH.UTM_sigma_gha_psh100.EKL.I_ni_Mu.pdf"

    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_NORTH.UTM_ni_Overview.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_NORTH.UTM_sigma_gha_psh100.EKL.I_ni_Overview.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_NORTH.UTM_ni_Overview.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_SI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_NORTH.UTM_sigma_gha_psh100.EKL.I_ni_Overview.pdf"

)

## Rund "pdftk".
pdftk "${pdfs[@]}" cat output "${output}"

## Store name of resulting .pdf file in variable "output".
output="Handouts/MasAr_Handout_2017-09-04_Spruce_4Terms_Splines.pdf"

## Create array containing the .pdf files to be concatenated.
pdfs=(

    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_psNORTH.UTM_ni_Mu.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_psNORTH.UTM_sigma_gha_psh100.EKL.I_ni_Mu.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_psNORTH.UTM_ni_Mu.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_psNORTH.UTM_sigma_gha_psh100.EKL.I_ni_Mu.pdf"

    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_psNORTH.UTM_ni_Overview.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_psh100.EKL.I_pshnn.neu_psNORTH.UTM_sigma_gha_psh100.EKL.I_ni_Overview.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_psNORTH.UTM_ni_Overview.pdf"
    "Models/GAMLSS/bart.spruce.clean.1.8/GAMLSS_BCCGo_mu_gha_psSI.h100.diff.EKL.I_pbmh100.EKL.I_pshnn.neu_psNORTH.UTM_sigma_gha_psh100.EKL.I_ni_Overview.pdf"

)

## Rund "pdftk".
pdftk "${pdfs[@]}" cat output "${output}"

exit
