#! /bin/bash

## Preamble.
cd ~/"laptop02_MasAr/Graphics/"

## Store name of resulting .pdf file in variable "output".
output="Handouts/MasAr_Handout_2017-05-24.pdf"

## Create array containing the .pdf files to be concatenated.
pdfs=( "bart.clean.alt_bart.clean.ksha.pdf"
       "bart.clean.h100_bart.clean.ksha.pdf"
       "bart.clean.h100_bart.clean.h100.diff.EKL.I.pdf"
       "bart.clean.ln.dg_bart.clean.ln.nha.pdf"
       "gam_gha_sh100.pdf"
       "gam_gha_sh100.EKL.I.pdf"
       "gam_gha_sSI.h100.pdf" )

## Rund "pdftk".
pdftk "${pdfs[@]}" cat output "${output}"

## printf "%s\n" "${pdfs[@]}"  ## TESTING

exit
